title: The Resume of Thomas A. Anderson (The One)
description: Prophesized by The Oracle to be The One, Thomas A. Anderson freed humanity from the Matrix and ended the Machine War.
theme: '#0074D9'
jobs: 3
schools: 1
references: false
